### ISSUE TITLE
运行MIX_ENV=prod mix release出错，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [Kabie/shadowsocks#1]
hi.

root@hb:~/shadowsocks-elixir-by-Kabie# MIX_ENV=prod mix release
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

==> erlware_commons (compile)
src/ec_plists.erl:220: syntax error before: '/'
src/ec_plists.erl:226: syntax error before: '/'
src/ec_plists.erl:250: syntax error before: '/'
src/ec_plists.erl:256: syntax error before: '/'
src/ec_plists.erl:279: syntax error before: '/'
src/ec_plists.erl:285: syntax error before: '/'
src/ec_plists.erl:300: syntax error before: '/'
src/ec_plists.erl:305: syntax error before: '/'
src/ec_plists.erl:326: syntax error before: '/'
src/ec_plists.erl:336: syntax error before: '/'
src/ec_plists.erl:343: syntax error before: '/'
src/ec_plists.erl:355: syntax error before: '/'
src/ec_plists.erl:361: syntax error before: '/'
src/ec_plists.erl:372: syntax error before: '/'
src/ec_plists.erl:384: syntax error before: '/'
src/ec_plists.erl:397: syntax error before: '/'
src/ec_plists.erl:403: syntax error before: '/'
src/ec_plists.erl:418: syntax error before: '/'
src/ec_plists.erl:427: syntax error before: '/'
src/ec_plists.erl:438: syntax error before: '/'
src/ec_plists.erl:450: syntax error before: '/'
src/ec_plists.erl:459: syntax error before: '/'
src/ec_plists.erl:472: syntax error before: '/'
src/ec_plists.erl:484: syntax error before: '/'
src/ec_plists.erl:522: syntax error before: '/'
src/ec_plists.erl:590: syntax error before: '/'
src/ec_plists.erl:625: syntax error before: '/'
src/ec_plists.erl:209: type el_fun() is unused
Compiling src/ec_plists.erl failed:
ERROR: compile failed while processing /root/shadowsocks-elixir-by-Kabie/deps/erlware_commons: rebar_abort
*\* (Mix) Could not compile dependency :erlware_commons, "/root/.mix/rebar compile skip_deps=true deps_dir="/root/shadowsocks-elixir-by-Kabie/_build/prod/lib"" command failed. You can recompile this dependency with "mix deps.compile erlware_commons", update it with "mix deps.update erlware_commons" or clean it with "mix deps.clean erlware_commons"
root@hb:~/shadowsocks-elixir-by-Kabie# 
root@hb:~/shadowsocks-elixir-by-Kabie# mix deps.compile erlware_commons
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

*\* (Mix) Unknown dependency erlware_commons for environment dev
root@hb:~/shadowsocks-elixir-by-Kabie#

thanks.

**Comment by Kabie** [comment]
I just replaced `exrm` with `distillery`, now it has no other dependencies.

**Comment by luckypoem** [comment]
hi.

我怀疑是不是我没有成功搭建elixir?
root@AR:~/shadowsocks-elixir-by-Kabie# /root/elixir/bin/mix deps.get
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
root@AR:~/shadowsocks-elixir-by-Kabie#

但我运行elixir又是正常的，
root@AR:~/shadowsocks-elixir-by-Kabie# /root/elixir/bin/elixir -h
Usage: elixir [options] [.exs file] [data]

  -v                          Prints version and exits
  -e COMMAND                  Evaluates the given command (_)
  -r FILE                     Requires the given files/patterns (_)
  -S SCRIPT                   Finds and executes the given script in PATH
  -pr FILE                    Requires the given files/patterns in parallel (_)
  -pa PATH                    Prepends the given path to Erlang code path (_)
  -pz PATH                    Appends the given path to Erlang code path (*)

  --app APP                   Starts the given app and its dependencies (_)
  --cookie COOKIE             Sets a cookie for this distributed node
  --detached                  Starts the Erlang VM detached from console
  --erl SWITCHES              Switches to be passed down to Erlang (_)
  --hidden                    Makes a hidden node
  --logger-otp-reports BOOL   Enables or disables OTP reporting
  --logger-sasl-reports BOOL  Enables or disables SASL reporting
  --name NAME                 Makes and assigns a name to the distributed node
  --no-halt                   Does not halt the Erlang VM after execution
  --sname NAME                Makes and assigns a short name to the distributed node
  --werl                      Uses Erlang's Windows shell GUI (Windows only)

*\* Options marked with (_) can be given more than once
*_ Options given after the .exs file or -- are passed down to the executed code
*\* Options can be passed to the Erlang runtime using ELIXIR_ERL_OPTIONS or --erl
root@AR:~/shadowsocks-elixir-by-Kabie# 

那么运行/root/elixir/bin/mix deps.get所显示的内容是正常的吗？
谢谢回复！

**Comment by Kabie** [comment]
你的Elixir版本和Erlang版本都是什么，怎么安装的？

**Comment by luckypoem** [comment]
我的elixir是如下编译的：（现在正常了，先头忘记运行make.不过下面还是有问题。）

git clone https://github.com/elixir-lang/elixir
cd elixir 
make  

会显示：
...
==> elixir (compile)
==> eex (compile)
==> mix (compile)
Generated mix app
==> ex_unit (compile)
Generated ex_unit app
==> logger (compile)
Generated logger app
Generated eex app
==> iex (compile)
Generated iex app
root@hb:~/elixir#

root@AR:~/shadowsocks-elixir-by-Kabie# elixir -v
Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [smp:24:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.0-dev (5c4e52c)
root@AR:~/shadowsocks-elixir-by-Kabie#

已经安装了erlang,版本是19:
root@AR:~/shadowsocks-elixir-by-Kabie/rel# erl
Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [smp:24:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.0  (abort with ^G)

现在运行mix deps.get和MIX_ENV=prod mix release --env=prod都正常：
运行MIX_ENV=prod mix release --env=prod 
显示：
Generated distillery app
==> shadowsocks
Compiling 6 files (.ex)
Generated shadowsocks app
==> Assembling release..
==> Building release shadowsocks:0.3.2 using environment prod
==> Including ERTS 8.0 from /usr/lib/erlang/erts-8.0
==> Packaging release..
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: rel/shadowsocks/bin/shadowsocks console
      Foreground: rel/shadowsocks/bin/shadowsocks foreground
      Daemon: rel/shadowsocks/bin/shadowsocks start
root@AR:~/shadowsocks-elixir-by-Kabie# 
root@AR:~/shadowsocks-elixir-by-Kabie# SHADOW_PASS=mypass rel/shadowsocks/bin/shadowsocks start
root@AR:~/shadowsocks-elixir-by-Kabie# 
root@AR:~/shadowsocks-elixir-by-Kabie# ps aux|grep shadowsocks
root     21894  0.0  0.0   2480   556 ?        S    9月07   0:00 /root/shadowsocks-elixir-by-kabie/rel/shadowsocks/erts-8.0/bin/epmd -daemon
root     27043  0.0  0.0   2692   760 ?        S    07:28   0:00 /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/bin/run_erl -daemon /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/tmp/erl_pipes/shadowsocks@127.0.0.1/ /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/log exec "/root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/bin/shadowsocks" "console" --  
root     27044  0.0  2.5 422916 45536 pts/0    Ssl+ 07:28   0:02 /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/bin/beam.smp -- -root /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks -progname root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/releases/0.3.2/shadowsocks.sh -- -home /root -- -boot /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/releases/0.3.2/shadowsocks -boot_var ERTS_LIB_DIR /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/lib/shadowsocks-0.3.2/consolidated -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib/sasl-3.0 -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib/iex-1.4.0-dev -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib/shadowsocks-0.3.2 -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib/kernel-5.0 -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib/stdlib-3.0 -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib/elixir-1.4.0-dev -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib/compiler-7.0 -pa /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/erts-8.0/../lib/logger-1.4.0-dev \ -name shadowsocks@127.0.0.1 -setcookie shadowsocks -smp auto -config /root/shadowsocks-elixir-by-Kabie/rel/shadowsocks/releases/0.3.2/sys.config -mode embedded -user Elixir.IEx.CLI -extra --no-halt +iex -- console --
root     27718  0.0  0.0   4664  1004 pts/3    S+   08:54   0:00 grep shadowsocks
root@AR:~/shadowsocks-elixir-by-Kabie#

进程shadowsocks确实在运行中，其pid为27043.但就是翻墙失败，不知为什么？
你确实用你这个shadowsocks成功翻墙过吗？

**Comment by Kabie** [comment]
是我配置错了。我自己都是 iex 的，没有 release 过 :sweat: 
现在应该好了。

**Comment by luckypoem** [comment]
hi。

今天再来你这里，这次搞定了：
git clone https://github.com/Kabie/shadowsocks kabie-shadowsocks
cd kabie-shadowsocks
mix  local.hex --force
mix deps.get
root@localhost:~/kabie-shadowsocks# SHADOW_PORT=8488 MIX_ENV=prod mix release --env=prod
会显示：
...
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/prod/rel/shadowsocks/bin/shadowsocks console
      Foreground: _build/prod/rel/shadowsocks/bin/shadowsocks foreground
      Daemon: _build/prod/rel/shadowsocks/bin/shadowsocks start
root@localhost:~/kabie-shadowsocks# SHADOW_PASS=mypass _build/prod/rel/shadowsocks/bin/shadowsocks start
root@localhost:~/kabie-shadowsocks#

服务器端就运行起来了。
设置ss客户端的参数：服务器的ip,端口：8488，密码：mypass，加密方式：默认为aes-128-cfb
设置浏览器的socks代理服务器地址为127.0.0.1:1080,即可翻墙。

不过在服务器上，如果我想改加密方式为aes-256-cfb，该怎么改？

**Comment by Kabie** [comment]
目前只支持aes_cfb， 配置 `SHADOW_KEYLEN` 默认为 16，也就是 8*16=128
设置为 24 就是aes-192-cfb, 32 就是aes-256-cfb
之后如果增加支持的协议，估计会修改配置方式

**Comment by luckypoem** [comment]
另外，在服务器上，你这个shadowsocks进程很容易退出。大约10分钟就退出了。怎么解决？

**Comment by luckypoem** [comment]
运行SHADOW_PASS=mypass _build/prod/rel/shadowsocks/bin/shadowsocks start不如运行
SHADOW_PASS=mypass _build/prod/rel/shadowsocks/bin/shadowsocks foreground > /dev/null &来得持久。
